CREATE TABLE `led_status` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `led1` TINYINT NOT NULL DEFAULT 0,
    `led2` TINYINT NOT NULL DEFAULT 0,
    `led3` TINYINT NOT NULL DEFAULT 0,
    `led4` TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`)
);
